djangostore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('store.urls', namespace='store')),
    path('order/', include('order.urls', namespace='order')),
    path('user/', include('userapp.urls', namespace='user')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'
urlpatterns = [
    path('cart/',OrderCreateView.as_view(), name='cart'),
    path('checkout/',OrderShowView.as_view(), name='checkout'),
    path('cart_actions/<int:product_id>/', CartActionsView.as_view(), name='cart_actions'),
]

store/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

app_name = 'store'

urlpatterns = [
    # main page
    path('', Indexview.as_view(), name='index'),
    # products listing by categories
    path('category/', CategoryProductsView.as_view(), name='products'),
    path('category/<slug:slug>/', CategoryProductsView.as_view(), name='products'),
    # product detailed page
    path('product/', ProductView.as_view(), name='product'),
    path('product/<slug:slug>/', ProductView.as_view(), name='product'),
    # contacts page
    path('contact/', ContactsView.as_view(template_name='contacts.html'), name='contacts'),
]

userapp/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
]

templates/partials/footer.html
{% load static %}
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
  <div class="container py-5">
    <div class="pb-4 mb-4"
         style="border-bottom: 1px solid rgba(226, 175, 24, 0.5)">
      <div class="row g-4">
        <div class="col-lg-3">
          <a href="#">
            <h1 class="text-primary mb-0">Fruitables</h1>
            <p class="text-secondary mb-0">Fresh products</p>
          </a>
        </div>
        <div class="col-lg-6">
          <div class="position-relative mx-auto">
            <input class="form-control border-0 w-100 py-3 px-4 rounded-pill"
                   type="number"
                   placeholder="Your Email">
            <button type="submit"
                    class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white"
                    style="top: 0;
                           right: 0">Subscribe Now</button>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="d-flex justify-content-end pt-3">
            <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle"
               href=""><i class="fab fa-twitter"></i></a>
            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle"
               href=""><i class="fab fa-facebook-f"></i></a>
            <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle"
               href=""><i class="fab fa-youtube"></i></a>
            <a class="btn btn-outline-secondary btn-md-square rounded-circle"
               href=""><i class="fab fa-linkedin-in"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="row g-5">
      <div class="col-lg-3 col-md-6">
        <div class="footer-item">
          <h4 class="text-light mb-3">Why People Like us!</h4>
          <p class="mb-4">
            typesetting, remaining essentially unchanged. It was
            popularised in the 1960s with the like Aldus PageMaker including of Lorem Ipsum.
          </p>
          <a href=""
             class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="d-flex flex-column text-start footer-item">
          <h4 class="text-light mb-3">Shop Info</h4>
          <a class="btn-link" href="">About Us</a>
          <a class="btn-link" href="">Contact Us</a>
          <a class="btn-link" href="">Privacy Policy</a>
          <a class="btn-link" href="">Terms & Condition</a>
          <a class="btn-link" href="">Return Policy</a>
          <a class="btn-link" href="">FAQs & Help</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="d-flex flex-column text-start footer-item">
          <h4 class="text-light mb-3">Account</h4>
          <a class="btn-link" href="">My Account</a>
          <a class="btn-link" href="">Shop details</a>
          <a class="btn-link" href="">Shopping Cart</a>
          <a class="btn-link" href="">Wishlist</a>
          <a class="btn-link" href="">Order History</a>
          <a class="btn-link" href="">International Orders</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="footer-item">
          <h4 class="text-light mb-3">Contact</h4>
          <p>Address: 1429 Netus Rd, NY 48247</p>
          <p>Email: Example@gmail.com</p>
          <p>Phone: +0123 4567 8910</p>
          <p>Payment Accepted</p>
          <img src="{% static 'img/payment.png' %}" class="img-fluid" alt="">
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Footer End -->

templates/partials/nav.html
{% load i18n %}
<!-- Navbar start -->
<div class="container-fluid fixed-top">
  <div class="container topbar bg-primary d-none d-lg-block">
    <div class="d-flex justify-content-between">
      <div class="top-info ps-2">
        <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">123 Street, New York</a></small>
        <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email@Example.com</a></small>
      </div>
      <div class="top-link pe-2">
        <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
        <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
        <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
      </div>
    </div>
  </div>
  <div class="container px-0">
    <nav class="navbar navbar-light bg-white navbar-expand-xl">
      <a href="{% url "store:index" %}" class="navbar-brand">
        <h1 class="text-primary display-6">Fruitables</h1>
      </a>
      <button class="navbar-toggler py-2 px-3"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarCollapse">
        <span class="fa fa-bars text-primary"></span>
      </button>
      <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
        <div class="navbar-nav mx-auto">
          <a href="{% url "store:index" %}" class="nav-item nav-link active">{% trans "Home" %}</a>
          <a href="{% url "store:products" %}" class="nav-item nav-link">{% trans "Shop" %}</a>
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">{% trans "Category" %}</a>
            <div class="dropdown-menu m-0 bg-secondary rounded-0">
              {% if root_categories %}
                {% for category in root_categories %}
                  {% if category.parent is None %}
                    <a href="{% url "store:products" category.slug %}" class='dropdown-item'>{{ category.name }}</a>
                  {% endif %}
                {% endfor %}
              {% else %}
                <p class='nav-item nav-link'>{% trans "no categories" %}</p>
              {% endif %}
            </div>
          </div>
          <a href="{% url "store:contacts" %}" class="nav-item nav-link">{% trans "Contacts" %}</a>
        </div>
        <div class="d-flex m-3 me-0">
          <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4"
                  data-bs-toggle="modal"
                  data-bs-target="#searchModal">
            <i class="fas fa-search text-primary"></i>
          </button>
          <a href="{% url 'order:cart' %}" class="position-relative me-4 my-auto">
            <i class="fa fa-shopping-bag fa-2x"></i>
            <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1"
                  style="top: -5px;
                         left: 15px;
                         height: 20px;
                         min-width: 20px">{{ total_products }}</span>
          </a>
          <div class="my-auto" style="position: relative;">
            <button id="btn-user"
                    class="my-auto"
                    style="border:none;
                           outline:none;
                           background:none;
                           color:#81c408">
              <i class="fas fa-user fa-2x"></i>
            </button>
            <ul id="user-menu"
                style="display: none;
                       position: absolute;
                       top: 110%;
                       left: 0;
                       background: white;
                       border: 1px solid #ccc;
                       border-radius:12px;
                       min-width:100px;
                       z-index: 1000;
                       padding: 5px 20px">
              {% if request.user.is_authenticated %}
                <li style="list-style-type:none">
                  <form action="{% url "user:logout" %}" method="POST">
                    {% csrf_token %}
                    <input type='submit'
                           value="{% trans 'Log Out' %}"
                           style="border:none;
                                  outline:none;
                                  background:none;
                                  color:#81c408" />
                  </form>
                </li>
              {% else %}
                <li style="list-style-type:none">
                  <a href="{% url "user:login" %}">{% trans "Log In" %}</a>
                </li>
                <li style="list-style-type:none">
                  <a href="{% url "user:register" %}">{% trans "Sign Up" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
          <form action="{% url 'set_language' %}" method="POST">
            {% csrf_token %}
            <select class="form-control form-control-sm"
                    id="langformcontrol"
                    name="language"
                    onchange="this.form.submit();">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <option value="{{ language.code }}"
                        {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
                  {{ language.name_local }} ({{ language.code }})
                </option>
              {% endfor %}
            </select>
          </form>
        </div>
      </div>
    </nav>
  </div>
</div>
<!-- Navbar End -->