djangostore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('store.urls', namespace='store')),
    path('order/', include('order.urls', namespace='order')),
    path('user/', include('userapp.urls', namespace='user')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'
urlpatterns = [
    path('cart/',OrderCreateView.as_view(), name='cart'),
    path('checkout/',OrderShowView.as_view(), name='checkout'),
    path('cart_actions/<int:product_id>/', CartActionsView.as_view(), name='cart_actions'),
]

order/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class UserCart(models.Model):
    user = models.OneToOneField("userapp.CustomUser", on_delete=models.CASCADE, related_name='cart', verbose_name=_('cart user'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('date creation'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('date update'))
    coupon_code = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = _('user cart')
        verbose_name_plural = _('user carts')
    


class CartItem(models.Model):
    cart = models.ForeignKey('order.UserCart', on_delete=models.CASCADE, related_name='cart_items')
    product = models.ForeignKey('store.Product', on_delete=models.CASCADE, related_name='cart_products')
    quantity = models.PositiveIntegerField(default=1, null=False, blank=True)
    action = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"cart of {self.cart.user.username}"

    class Meta:
        unique_together = ('cart', 'product')  

order/forms.py
from django import forms
from .models import CartItem, UserCart
from django.core.exceptions import ValidationError 

class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['quantity', 'action']

    def __init__(self, *args, product, **kwargs):
        super().__init__(*args, **kwargs)
        self.product = product


    def clean(self):
        cleaned_data = super().clean()
        quantity = cleaned_data.get('quantity') or 1

        if quantity > self.product.quantity:
            raise ValidationError('not enough products!')

        return cleaned_data
    
    def update_cart_item(self, user):
        cleaned_data = self.cleaned_data
        quantity = cleaned_data['quantity']
        action = cleaned_data['action']

        cart = UserCart.objects.get(user=user)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=self.product)

        if action == 'add':
            if created:
                cart_item.quantity = quantity
            else:
                cart_item.quantity += quantity

        elif action == 'decrease':
            cart_item.quantity -= quantity
            if cart_item.quantity <= 0:
                cart_item.delete()
                return None  
            
        elif action == 'delete':
            cart_item.delete()
            return None  

        cart_item.save()
        return cart_item

order/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from store.models import Product
from .forms import CartItemForm
from .models import UserCart
from django.db.models import F
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import RedirectView


# parent view for cart and checkout views
class BaseCartView(LoginRequiredMixin, View):
    shipping_cost = 3 

    def get_cart_context(self, request):
        cart = UserCart.objects.get(user=request.user)
        cart_items = cart.cart_items.annotate(total_price=F('product__price') * F('quantity'))

        subtotal = sum(item.total_price for item in cart_items)
        total = subtotal + self.shipping_cost

        return {
            'cart_items': cart_items,
            'subtotal': subtotal,
            'total': total,
            'shipping_cost': self.shipping_cost,
        }
    

class OrderCreateView(BaseCartView):
    template_name = 'cart.html'

    def get(self, request, *args, **kwargs):
        context = self.get_cart_context(request)
        return render(request, self.template_name, context)


class OrderShowView(BaseCartView):
    template_name = 'checkout.html'

    def get(self, request, *args, **kwargs):
        context = self.get_cart_context(request)
        # change cart_items key into cart for checkout template  
        context['cart'] = context.pop('cart_items') 
        return render(request, self.template_name, context)



class CartActionsView(LoginRequiredMixin,RedirectView):

    def post(self, request, product_id, *args, **kwargs):
        product = get_object_or_404(Product, id=product_id)
        form = CartItemForm(request.POST, product=product)

        if form.is_valid():
            form.update_cart_item(request.user)
        else:
            return HttpResponse('Invalid input values', status=400)

        referer = request.META.get('HTTP_REFERER', 'order:cart')
        return redirect(referer)
    
    

order/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">Cart</h1>
    <ol class="breadcrumb justify-content-center mb-0">
      <li class="breadcrumb-item">
        <a href="#">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="#">Pages</a>
      </li>
      <li class="breadcrumb-item active text-white">Cart</li>
    </ol>
  </div>
  <div class="container-fluid py-5">
    <div class="container py-5">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Products</th>
              <th scope="col">Name</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total</th>
              <th scope="col">Handle</th>
            </tr>
          </thead>
          <tbody>
            {% for item in cart_items %}
              <tr>
                <th scope="row">
                  <div class="d-flex align-items-center">
                    <img src="{{ item.product.image.url }}"
                         class="img-fluid me-5 rounded-circle"
                         style="width: 80px;
                                height: 80px"
                         alt="">
                  </div>
                </th>
                <td>
                  <p class="mb-0 mt-4">{{ item.product.name }}</p>
                </td>
                <td>
                  <p class="mb-0 mt-4">{{ item.product.price }}$</p>
                </td>
                <td>
                  <div class="input-group mt-4" style="width: 100px;">
                    <div class="input-group-btn">
                      <form id='form1'
                            action="{% url "order:cart_actions" item.product.id %}"
                            method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="decrease">
                        <input type="hidden" name="quantity" value="1">
                        <button class="btn btn-sm btn-minus rounded-circle bg-light border"
                                type="submit">
                          <i class="fa fa-minus"></i>
                        </button>
                      </form>
                    </div>
                    <span class="form-control form-control-sm text-center border-0">{{ item.quantity }}</span>
                    <div class="input-group-btn">
                      <form id='form2'
                            action="{% url "order:cart_actions" item.product.id %}"
                            method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="add">
                        <input type="hidden" name="quantity" value="1">
                        <button class="btn btn-sm btn-plus rounded-circle bg-light border"
                                type="submit">
                          <i class="fa fa-plus"></i>
                        </button>
                      </form>
                    </div>
                  </div>
                </td>
                <td>
                  <p class="mb-0 mt-4">{{ item.total_price }} $</p>
                </td>
                <td>
                  <form id="form3"
                        action="{% url "order:cart_actions" item.product.id %}"
                        method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="delete">
                    <input type="hidden" name="quantity" value="1">
                    <button class="btn btn-md rounded-circle bg-light border mt-4" type="submit">
                      <i class="fa fa-times text-danger"></i>
                    </button>
                  </form>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="mt-5">
        <input type="text"
               class="border-0 border-bottom rounded me-5 py-3 mb-4"
               placeholder="Coupon Code">
        <button class="btn border-secondary rounded-pill px-4 py-3 text-primary"
                type="button">Apply Coupon</button>
      </div>
      <div class="row g-4 justify-content-end">
        <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
          <div class="bg-light rounded">
            <div class="p-4">
              <h1 class="display-6 mb-4">
                Cart <span class="fw-normal">Total</span>
              </h1>
              <div class="d-flex justify-content-between mb-4">
                <h5 class="mb-0 me-4">Subtotal:</h5>
                <p class="mb-0">$ {{ subtotal }}</p>
              </div>
              <div class="d-flex justify-content-between">
                <h5 class="mb-0 me-4">Shipping</h5>
                <div>
                  <p class="mb-0">Flat rate: $ {{ shipping_cost }}</p>
                </div>
              </div>
              <p class="mb-0 text-end">Shipping to Ukraine.</p>
            </div>
            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
              <h5 class="mb-0 ps-4 me-4">Total</h5>
              <p class="mb-0 pe-4">$ {{ total }}</p>
            </div>
            <a href="{% url 'order:checkout' %}"
               class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4"
               type="button">Proceed Checkout</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

order/templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <!-- Single Page Header start -->
  <div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">Checkout</h1>
    <ol class="breadcrumb justify-content-center mb-0">
      <li class="breadcrumb-item">
        <a href="#">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="#">Pages</a>
      </li>
      <li class="breadcrumb-item active text-white">Checkout</li>
    </ol>
  </div>
  <!-- Single Page Header End -->
  <!-- Checkout Page Start -->
  <div class="container-fluid py-5">
    <div class="container py-5">
      <h1 class="mb-4">Billing details</h1>
      <form action="#">
        <div class="row g-5">
          <div class="col-md-12 col-lg-6 col-xl-7">
            <div class="row">
              <div class="col-md-12 col-lg-6">
                <div class="form-item w-100">
                  <label class="form-label my-3">
                    First Name<sup>*</sup>
                  </label>
                  <input type="text" class="form-control">
                </div>
              </div>
              <div class="col-md-12 col-lg-6">
                <div class="form-item w-100">
                  <label class="form-label my-3">
                    Last Name<sup>*</sup>
                  </label>
                  <input type="text" class="form-control">
                </div>
              </div>
            </div>
            <div class="form-item">
              <label class="form-label my-3">
                Company Name<sup>*</sup>
              </label>
              <input type="text" class="form-control">
            </div>
            <div class="form-item">
              <label class="form-label my-3">
                Address <sup>*</sup>
              </label>
              <input type="text"
                     class="form-control"
                     placeholder="House Number Street Name">
            </div>
            <div class="form-item">
              <label class="form-label my-3">
                Town/City<sup>*</sup>
              </label>
              <input type="text" class="form-control">
            </div>
            <div class="form-item">
              <label class="form-label my-3">
                Country<sup>*</sup>
              </label>
              <input type="text" class="form-control">
            </div>
            <div class="form-item">
              <label class="form-label my-3">
                Postcode/Zip<sup>*</sup>
              </label>
              <input type="text" class="form-control">
            </div>
            <div class="form-item">
              <label class="form-label my-3">
                Mobile<sup>*</sup>
              </label>
              <input type="tel" class="form-control">
            </div>
            <div class="form-item">
              <label class="form-label my-3">
                Email Address<sup>*</sup>
              </label>
              <input type="email" class="form-control">
            </div>
            <div class="form-check my-3">
              <input type="checkbox"
                     class="form-check-input"
                     id="Account-1"
                     name="Accounts"
                     value="Accounts">
              <label class="form-check-label" for="Account-1">Create an account?</label>
            </div>
            <hr>
            <div class="form-check my-3">
              <input class="form-check-input"
                     type="checkbox"
                     id="Address-1"
                     name="Address"
                     value="Address">
              <label class="form-check-label" for="Address-1">Ship to a different address?</label>
            </div>
            <div class="form-item">
              <textarea name="text"
                        class="form-control"
                        spellcheck="false"
                        cols="30"
                        rows="11"
                        placeholder="Oreder Notes (Optional)"></textarea>
            </div>
          </div>
          <div class="col-md-12 col-lg-6 col-xl-5">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Products</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in cart %}
                    <tr>
                      <th scope="row">
                        <div class="d-flex align-items-center mt-2">
                          <img src="{{ item.product.image.url }}"
                               class="img-fluid rounded-circle"
                               style="width: 90px;
                                      height: 90px"
                               alt="">
                        </div>
                      </th>
                      <td class="py-5">{{ item.product.title }}</td>
                      <td class="py-5">${{ item.product.price }}</td>
                      <td class="py-5">{{ item.quantity }}</td>
                      <td class="py-5">${{ item.total_price }}</td>
                    </tr>
                  {% endfor %}
                  <tr>
                    <th scope="row"></th>
                    <td class="py-5"></td>
                    <td class="py-5"></td>
                    <td class="py-5">
                      <p class="mb-0 text-dark py-3">Subtotal</p>
                    </td>
                    <td class="py-5">
                      <div class="py-3 border-bottom border-top">
                        <p class="mb-0 text-dark">${{ subtotal }}</p>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <th scope="row"></th>
                    <td class="py-5"></td>
                    <td class="py-5"></td>
                    <td class="py-5">
                      <p class="mb-0 text-dark py-3">Shipping</p>
                    </td>
                    <td class="py-5">
                      <div class="py-3 border-bottom border-top">
                        <p class="mb-0 text-dark">$ {{ shipping_cost }}</p>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <th scope="row"></th>
                    <td class="py-5">
                      <p class="mb-0 text-dark text-uppercase py-3">TOTAL</p>
                    </td>
                    <td class="py-5"></td>
                    <td class="py-5"></td>
                    <td class="py-5">
                      <div class="py-3 border-bottom border-top">
                        <p class="mb-0 text-dark">${{ total }}</p>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
              <div class="col-12">
                <div class="form-check text-start my-3">
                  <input type="checkbox"
                         class="form-check-input bg-primary border-0"
                         id="Transfer-1"
                         name="Transfer"
                         value="Transfer">
                  <label class="form-check-label" for="Transfer-1">Direct Bank Transfer</label>
                </div>
                <p class="text-start text-dark">
                  Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.
                </p>
              </div>
            </div>
            <div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
              <div class="col-12">
                <div class="form-check text-start my-3">
                  <input type="checkbox"
                         class="form-check-input bg-primary border-0"
                         id="Payments-1"
                         name="Payments"
                         value="Payments">
                  <label class="form-check-label" for="Payments-1">Check Payments</label>
                </div>
              </div>
            </div>
            <div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
              <div class="col-12">
                <div class="form-check text-start my-3">
                  <input type="checkbox"
                         class="form-check-input bg-primary border-0"
                         id="Delivery-1"
                         name="Delivery"
                         value="Delivery">
                  <label class="form-check-label" for="Delivery-1">Cash On Delivery</label>
                </div>
              </div>
            </div>
            <div class="row g-4 text-center align-items-center justify-content-center border-bottom py-3">
              <div class="col-12">
                <div class="form-check text-start my-3">
                  <input type="checkbox"
                         class="form-check-input bg-primary border-0"
                         id="Paypal-1"
                         name="Paypal"
                         value="Paypal">
                  <label class="form-check-label" for="Paypal-1">Paypal</label>
                </div>
              </div>
            </div>
            <div class="row g-4 text-center align-items-center justify-content-center pt-4">
              <button type="button"
                      class="btn border-secondary py-3 px-4 text-uppercase w-100 text-primary">Place Order</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- Checkout Page End -->
{% endblock content %}