djangostore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('store.urls', namespace='store')),
    path('order/', include('order.urls', namespace='order')),
    path('user/', include('userapp.urls', namespace='user')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'
urlpatterns = [
    path('cart/',OrderCreateView.as_view(), name='cart'),
    path('checkout/',OrderShowView.as_view(), name='checkout'),
    path('cart_actions/<int:product_id>/', CartActionsView.as_view(), name='cart_actions'),
]

store/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

app_name = 'store'

urlpatterns = [
    # main page
    path('', Indexview.as_view(), name='index'),
    # products listing by categories
    path('category/', CategoryProductsView.as_view(), name='products'),
    path('category/<slug:slug>/', CategoryProductsView.as_view(), name='products'),
    # product detailed page
    path('product/', ProductView.as_view(), name='product'),
    path('product/<slug:slug>/', ProductView.as_view(), name='product'),
    # contacts page
    path('contact/', ContactsView.as_view(template_name='contacts.html'), name='contacts'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
      <head>
            <meta charset="utf-8">
            <title>Fruitables - Vegetable Website Template</title>
            <meta content="width=device-width, initial-scale=1.0" name="viewport">
            <meta content="" name="keywords">
            <meta content="" name="description">
            <!-- Google Web Fonts -->
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap"
                  rel="stylesheet">
            <!-- Icon Font Stylesheet -->
            <link rel="stylesheet"
                  href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
                  rel="stylesheet">
            <!-- Libraries Stylesheet -->
            <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}"
                  rel="stylesheet">
            <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"
                  rel="stylesheet">
            <!-- Customized Bootstrap Stylesheet -->
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <!-- Template Stylesheet -->
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
      </head>
      <body>
            {% include "partials/nav.html" %}
            <!-- Spinner Start -->
            <div id="spinner"
                 class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
                  <div class="spinner-grow text-primary" role="status"></div>
            </div>
            <!-- Spinner End -->
            {% block content %}
            {% endblock content %}
            {% include "partials/footer.html" %}
            <!-- Copyright Start -->
            <div class="container-fluid copyright bg-dark py-4">
                  <div class="container">
                        <div class="row">
                              <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                                    <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>Your Site Name</a>, All right reserved.</span>
                              </div>
                              <div class="col-md-6 my-auto text-center text-md-end text-white">
                                    <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                                    <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                                    <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a> Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                              </div>
                        </div>
                  </div>
            </div>
            <!-- Copyright End -->
            <!-- Back to Top -->
            <a href="#"
               class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>
            <!-- JavaScript Libraries -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
            <script src="{% static 'lib/easing/easing.min.js' %}"></script>
            <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
            <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
            <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
            <!-- Template Javascript -->
            <script src="{% static 'js/main.js' %}"></script>
            <script src="{% static 'js/custom.js' %}"></script>
      </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
    <!-- Modal Search Start -->
    <div class="modal fade"
         id="searchModal"
         tabindex="-1"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <form id="search_form"
                      method="POST"
                      action="{% url "store:products" %}"
                      class="modal-body d-flex align-items-center">
                    {% csrf_token %}
                    <div class="input-group w-75 mx-auto d-flex">
                        <input type="text"
                               id="product_name"
                               name="product_name"
                               class="form-control p-3"
                               placeholder="search product by name">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Modal Search End -->
    <!-- Hero Start -->
    <div class="container-fluid py-5 mb-5 hero-header">
        <div class="container py-5">
            <div class="row g-5 align-items-center">
                <div class="col-md-12 col-lg-7">
                    <h4 class="mb-3 text-secondary">100% Organic Foods</h4>
                    <h1 class="mb-5 display-3 text-primary">Organic Veggies & Fruits Foods</h1>
                    <div class="position-relative mx-auto">
                        <input class="form-control border-2 border-secondary w-75 py-3 px-4 rounded-pill"
                               type="number"
                               placeholder="Search">
                        <button type="submit"
                                class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-100"
                                style="top: 0;
                                       right: 25%">Submit Now</button>
                    </div>
                </div>
                <div class="col-md-12 col-lg-5">
                    <div id="carouselId"
                         class="carousel slide position-relative"
                         data-bs-ride="carousel">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active rounded">
                                <img src="{% static 'img/hero-img-1.png' %}"
                                     class="img-fluid w-100 h-100 bg-secondary rounded"
                                     alt="First slide">
                                <a href="#" class="btn px-4 py-2 text-white rounded">Fruites</a>
                            </div>
                            <div class="carousel-item rounded">
                                <img src="{% static 'img/hero-img-1.png' %}"
                                     class="img-fluid w-100 h-100 rounded"
                                     alt="Second slide">
                                <a href="#" class="btn px-4 py-2 text-white rounded">Vesitables</a>
                            </div>
                        </div>
                        <button class="carousel-control-prev"
                                type="button"
                                data-bs-target="#carouselId"
                                data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next"
                                type="button"
                                data-bs-target="#carouselId"
                                data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->
    <!-- Fruits Shop Start-->
    <div class="container-fluid fruite py-5">
        <div class="container py-5">
            <div class="tab-class text-center">
                <div class="row g-4">
                    <div class="col-lg-4 text-start">
                        <h1>{% trans "Top Rated Products" %}</h1>
                    </div>
                </div>
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane fade show p-0 active">
                        <div class="row g-4">
                            <div class="col-lg-12">
                                <div class="row g-4">
                                    {% for product in products %}
                                        {% include "product_card.html" with product=product %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Tastimonial Start -->
    <div class="container-fluid testimonial py-5">
        <div class="container py-5">
            <div class="testimonial-header text-center">
                <h4 class="text-primary">Our Testimonial</h4>
                <h1 class="display-5 mb-5 text-dark">{% trans "Our Client Saying!" %}</h1>
            </div>
            <div class="owl-carousel testimonial-carousel">
                <div class="testimonial-item img-border-radius bg-light rounded p-4">
                    <div class="position-relative">
                        <i class="fa fa-quote-right fa-2x text-secondary position-absolute"
                           style="bottom: 30px;
                                  right: 0"></i>
                        <div class="mb-4 pb-4 border-bottom border-secondary">
                            <p class="mb-0">
                                Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ever since the 1500s,
                            </p>
                        </div>
                        <div class="d-flex align-items-center flex-nowrap">
                            <div class="bg-secondary rounded">
                                <img src="{% static 'img/testimonial-1.jpg' %}"
                                     class="img-fluid rounded"
                                     style="width: 100px;
                                            height: 100px"
                                     alt="">
                            </div>
                            <div class="ms-4 d-block">
                                <h4 class="text-dark">Client Name</h4>
                                <p class="m-0 pb-3">Profession</p>
                                <div class="d-flex pe-5">
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="testimonial-item img-border-radius bg-light rounded p-4">
                    <div class="position-relative">
                        <i class="fa fa-quote-right fa-2x text-secondary position-absolute"
                           style="bottom: 30px;
                                  right: 0"></i>
                        <div class="mb-4 pb-4 border-bottom border-secondary">
                            <p class="mb-0">
                                Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ever since the 1500s,
                            </p>
                        </div>
                        <div class="d-flex align-items-center flex-nowrap">
                            <div class="bg-secondary rounded">
                                <img src="{% static 'img/testimonial-1.jpg' %}"
                                     class="img-fluid rounded"
                                     style="width: 100px;
                                            height: 100px"
                                     alt="">
                            </div>
                            <div class="ms-4 d-block">
                                <h4 class="text-dark">Client Name</h4>
                                <p class="m-0 pb-3">Profession</p>
                                <div class="d-flex pe-5">
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="testimonial-item img-border-radius bg-light rounded p-4">
                    <div class="position-relative">
                        <i class="fa fa-quote-right fa-2x text-secondary position-absolute"
                           style="bottom: 30px;
                                  right: 0"></i>
                        <div class="mb-4 pb-4 border-bottom border-secondary">
                            <p class="mb-0">
                                Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ever since the 1500s,
                            </p>
                        </div>
                        <div class="d-flex align-items-center flex-nowrap">
                            <div class="bg-secondary rounded">
                                <img src="{% static 'img/testimonial-1.jpg' %}"
                                     class="img-fluid rounded"
                                     style="width: 100px;
                                            height: 100px"
                                     alt="">
                            </div>
                            <div class="ms-4 d-block">
                                <h4 class="text-dark">Client Name</h4>
                                <p class="m-0 pb-3">Profession</p>
                                <div class="d-flex pe-5">
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                    <i class="fas fa-star text-primary"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Tastimonial End -->
{% endblock content %}

templates/product_card.html
{% load i18n %}
<form action="{% url "order:cart_actions" product.id %}"
      method="POST"
      class="col-md-6 col-lg-6 col-xl-4">
  {% csrf_token %}
  <input type="hidden" name="action" value='add'>
  <input type="hidden" name="quantity" value='1'>
  <div class="rounded position-relative fruite-item">
    <div class="fruite-img">
      <img src="{{ product.image.url }}"
           class="img-fluid w-100 rounded-top"
           alt="">
    </div>
    {% for tag in product.tag.all %}
      <div class="text-white bg-secondary px-3 py-1 rounded position-absolute"
           style="top: 10px;
                  left: 10px">{{ tag }}</div>
    {% endfor %}
    <div class="p-4 border border-secondary border-top-0 rounded-bottom">
      <h4>{{ product.name }}</h4>
      <p class="text-dark fs-5 fw-bold mb-0">${{ product.price }} / kg</p>
      <button type="submit"
              class="btn border border-secondary rounded-pill px-3 text-primary">
        <i class="fa fa-shopping-bag me-2 text-primary"></i> {% trans "Add to cart" %}
      </button>
      <br>
      <a href="{% url "store:product" product.slug %}"
         class="btn border border-secondary rounded-pill px-3 my-1 text-primary">{% trans "See Product" %}</a>
    </div>
  </div>
</form>

templates/success-message.html
{% if messages %}
  <ul id="messages"
      style="background:white;
             position:absolute;
             top:20px;
             left:50%;
             transform:translate(-50%);
             z-index:1000000;
             padding:12px;
             border:none;
             border-radius:20px">
    {% for message in messages %}<li style="color:green;list-style-type:none;">{{ message }}</li>{% endfor %}
  </ul>
{% endif %}