djangostore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('store.urls', namespace='store')),
    path('order/', include('order.urls', namespace='order')),
    path('user/', include('userapp.urls', namespace='user')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'
urlpatterns = [
    path('cart/',OrderCreateView.as_view(), name='cart'),
    path('checkout/',OrderShowView.as_view(), name='checkout'),
    path('cart_actions/<int:product_id>/', CartActionsView.as_view(), name='cart_actions'),
]

store/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

app_name = 'store'

urlpatterns = [
    # main page
    path('', Indexview.as_view(), name='index'),
    # products listing by categories
    path('category/', CategoryProductsView.as_view(), name='products'),
    path('category/<slug:slug>/', CategoryProductsView.as_view(), name='products'),
    # product detailed page
    path('product/', ProductView.as_view(), name='product'),
    path('product/<slug:slug>/', ProductView.as_view(), name='product'),
    # contacts page
    path('contact/', ContactsView.as_view(template_name='contacts.html'), name='contacts'),
]

store/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext_lazy as _

class Category(MPTTModel):
    name = models.CharField(max_length=255, unique=True, verbose_name=_('name'))
    slug = models.SlugField(unique=True, max_length=200, verbose_name=_('slug')) 
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='subcategory', verbose_name=_('parent'))
    description = models.TextField(blank=True, null=True, verbose_name=_('description'))
    image = models.ImageField(upload_to='categories/', blank=True, null=True, verbose_name=_('image'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('date update'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('date creation'))
    
    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _('categories')
        
    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name=_('name'))
    slug = models.SlugField(unique=True, max_length=200, verbose_name=_('slug')) 
    description = models.TextField(null=True, blank=True, verbose_name=_('description'))
    price = models.DecimalField(default=1, max_digits=10, decimal_places=2, null=False, verbose_name=_('price'))
    quantity = models.PositiveIntegerField(default=1, blank=True, null=True, verbose_name=_('quantity'))
    weight = models.PositiveIntegerField(default=1, null=True, blank=True, verbose_name=_('weight'))
    origin = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('origin'))
    quality = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('quality'))
    healthy = models.BooleanField(default=True, verbose_name=_('healthy'))
    is_published = models.BooleanField(default=False, verbose_name=_('is published'))
    image = models.ImageField(upload_to='products/', null=False, blank=False, verbose_name=_('image'))
    category = models.ManyToManyField('store.Category', related_name='products', verbose_name=_('category'))
    tag = models.ManyToManyField('store.ProductTag', related_name='products', verbose_name=_('tag'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('date update'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('date creation'))
    
    class Meta:
        verbose_name = _("product")
        verbose_name_plural = _('products')

    def __str__(self):
        return self.name


class ProductTag(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name=_('name'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('date update'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('date creation'))

    class Meta:
        verbose_name = _("product tag")
        verbose_name_plural = _('produtc tags')

    def __str__(self):
        return self.name

store/forms.py
from django import forms

class ProductForm(forms.Form):
    product_name = forms.CharField(max_length=255, required=False)
    product_price = forms.IntegerField(required=False)
    product_tag = forms.CharField(max_length=255, required=False)
    product_sort_list = forms.ChoiceField(choices=[
        ('price_up', 'Price Up'),
        ('price_down', 'Price Down'),
        ('created_at', 'Created At'),
    ], required=False)


class SendEmailForm(forms.Form):
    name = forms.CharField(max_length=255, required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(min_length=20, required=True)

store/views.py
from .models import Category, Product, ProductTag
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.views.generic import ListView, DetailView, FormView
from django.db.models import Count
from store.forms import ProductForm, SendEmailForm
from django.views import View
from django.core.cache import cache
from django.core import mail
from django.http import HttpResponse
from django.urls import reverse_lazy
from userapp.models import CustomUser
from django.contrib import messages
from .utils import get_top_rated_product

class Indexview (View):

    def get(self, request):
        
        root_categories = cache.get('root_categories_cache')
        if root_categories is None:
            root_categories = Category.objects.filter(parent__isnull=True)
            cache.set('root_categories_cache', root_categories, 60 * 1)

        categories = cache.get('categories_cache')
        if categories is None:
            categories = root_categories.get_descendants(include_self=True)
            cache.set('categories_cache', categories, 60 * 1)

        products = cache.get('products_cache')
        if products is None:
            products = get_top_rated_product(limit=5).order_by('-price')
            cache.set('products_cache', products, 60 * 1)

        context = {'root_categories': root_categories,'categories': categories, 'products': products}

        return render(request, 'index.html', context)


class CategoryProductsView(ListView):
    model = Product
    template_name = 'category_products.html'
    context_object_name = 'products'
    paginate_by = 3 

    def get_queryset(self):

        slug = self.kwargs.get('slug')
        root_categories = cache.get('root_categories_cache')
        if root_categories is None:
            root_categories = Category.objects.filter(parent__isnull=True)
            cache.set('root_categories_cache', root_categories, 60 * 1)

        if slug:
            selected_category = get_object_or_404(Category, slug=slug)
            products = cache.get(f'selected_category_{slug}_products_cache')
            if products is None:
                products = Product.objects.filter(category=selected_category).distinct().prefetch_related('tag')
                cache.set(f'selected_category_{slug}_products_cache', products)

            self.categories = selected_category.get_children().annotate(product_count=Count('products'))
        else:
            self.categories = root_categories.annotate(product_count=Count('products'))
            
            products = cache.get('products_cache')
            if products is None:
                products = Product.objects.filter(category__in=self.categories).distinct().prefetch_related('tag')
                cache.set('products_cache', products, 60 * 1)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = self.categories
        context['slug'] = self.kwargs.get('slug')
        context['tags'] = ProductTag.objects.all().distinct()
        context['get_elided_page_range'] = context['paginator'].get_elided_page_range(
            self.request.GET.get(self.page_kwarg, 1)
            )

        # pass modified url to context for preserve filters on page switches
        get_url_copy = self.request.GET.copy()
        if get_url_copy.get('page'):
            get_url_copy.pop('page')
        context['copied_url'] = get_url_copy

        return context

    def get(self, request, *args, **kwargs):
        form = ProductForm(request.GET)
        if form.is_valid():
            queryset = self.get_queryset()

            product_name = form.cleaned_data['product_name']
            product_price = form.cleaned_data['product_price']
            tag = form.cleaned_data['product_tag']
            sort_option = form.cleaned_data['product_sort_list']

            if product_name:
                queryset = queryset.filter(name__icontains=product_name)
            if product_price:
                queryset = queryset.filter(price__lte=product_price)
            if tag:
                queryset = queryset.filter(tag__name__icontains=tag)

            if sort_option == 'price_up':
                queryset = queryset.order_by('price')
            elif sort_option == 'price_down':
                queryset = queryset.order_by('-price')
            elif sort_option == 'created_at':
                queryset = queryset.order_by('-created_at')

            self.object_list = queryset
            context = self.get_context_data()
            return self.render_to_response(context)

        else:
            return HttpResponse('form validation error', 400)


# Product detailed page
class ProductView(DetailView):
    model = Product
    template_name= 'product.html'
    queryset= Product.objects.prefetch_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object

        context['category'] = product.category.annotate(product_count=Count('products')) 

        return context
    

class ContactsView(FormView):
    success_url = '.'
    template_name = 'contacts.html'
    form_class = SendEmailForm

    #if submitted data is valid, send email and redirect to main page.
    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        admin_users = CustomUser.objects.filter(is_superuser=True)
        admin_emails = admin_users.values_list('email', flat=True)

        try:
            mail.send_mail(
                'New user sent message.',
                cleaned_data.get('message'),
                cleaned_data.get('email'),
                admin_emails
            )
            messages.success(self.request, 'Your message has been sent succesfully! :)')
        except mail.BadHeaderError:
            return HttpResponse("Invalid header found.")
        
        return super().form_valid(form)

store/templates/category_products.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
  <!-- Modal Search Start -->
  <div class="modal fade"
       id="searchModal"
       tabindex="-1"
       aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content rounded-0">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"></button>
        </div>
        <form id="search_form"
              method="GET"
              action="."
              class="modal-body d-flex align-items-center">
          {% csrf_token %}
          <div class="input-group w-75 mx-auto d-flex">
            <input type="text"
                   id="product_name"
                   name="product_name"
                   class="form-control p-3"
                   placeholder="{% trans 'product name' %}"
                   value="{{ request.GET.product_name|default:'' }}">
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- Modal Search End -->
  <!-- Single Page Header start -->
  <div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">{% trans "Shop" %}</h1>
    <ol class="breadcrumb justify-content-center mb-0">
      <li class="breadcrumb-item">
        <a href="{% url 'store:index' %}">{% trans "Home" %}</a>
      </li>
      <li class="breadcrumb-item">
        <a href="{% url 'store:products' %}">{% trans "Shop" %}</a>
      </li>
      {% if slug %}
        <li class="breadcrumb-item text-white">
          <a href="{% url 'store:products' slug %}">{{ slug }}</a>
        </li>
      {% endif %}
    </ol>
  </div>
  <!-- Single Page Header End -->
  <!-- Fruits Shop Start-->
  <div class="container-fluid fruite py-5">
    <div class="container py-5">
      <h1 class="mb-4">{% trans "Fresh Fruits Shop" %}</h1>
      <div class="row g-4">
        <div class="col-lg-12">
          <div class="row g-4">
            <div class="col-xl-3">
              <div class="input-group w-100 mx-auto d-flex">
                <input type="search"
                       id="product_name"
                       name="product_name"
                       class="form-control p-3"
                       placeholder="{% trans 'product name' %}"
                       value="{{ request.GET.product_name|default:'' }}"
                       form="products-form">
              </div>
            </div>
            <div class="col-6"></div>
            <div class="col-xl-3">
              <div class="bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4">
                <label for="product_sort_list">{% trans "Sort By" %}:</label>
                <select id="product_sort_list"
                        name="product_sort_list"
                        class="border-0 form-select-sm bg-light me-3"
                        form="products-form">
                  <option value="price_up"
                          {% if request.GET.product_sort_list == 'price_up' %}selected{% endif %}>Price Up</option>
                  <option value="price_down"
                          {% if request.GET.product_sort_list == 'price_down' %}selected{% endif %}>Price Down</option>
                  <option value="created_at"
                          {% if request.GET.product_sort_list == 'created_at' %}selected{% endif %}>Created at</option>
                </select>
              </div>
            </div>
          </div>
          <div class="row g-4">
            <form action="." method="GET" class="col-lg-3" id="products-form">
              <div class="row g-4">
                <div class="col-lg-12">
                  <div class="mb-3">
                    <h4>{% trans "Categories" %}</h4>
                    <ul class="list-unstyled fruite-categorie">
                      {% for category in categories %}
                        <li>
                          <div class="d-flex justify-content-between fruite-name">
                            <a href="{% url 'store:products' category.slug %}"><i class="fas fa-apple-alt me-2"></i>{{ category.name }}</a>
                            <span>({{ category.product_count }})</span>
                          </div>
                        </li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="mb-3">
                    <h4 class="mb-2">{% trans "Max Price" %}</h4>
                    <input type="range"
                           class="form-range"
                           id="product_price"
                           name="product_price"
                           min="5"
                           max="500"
                           value="{{ request.GET.product_price|default:5 }}"
                           oninput="document.getElementById('product_price_value').textContent = this.value"
                           form="products-form">
                    <output name="product_price" form="products-form" id="product_price_value">{{ request.GET.product_price|default:5 }}</output>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="mb-3">
                    <h4>{% trans "Tags" %}</h4>
                    {% for tag in tags %}
                      <div class="mb-2">
                        <input type="radio"
                               class="me-2"
                               id="product_tag_{{ tag.name }}"
                               name="product_tag"
                               value="{{ tag.name }}"
                               {% if request.GET.product_tag == tag.name %}checked{% endif %}
                               form="products-form">
                        <label for="product_tag_{{ tag.name }}">{{ tag.name }}</label>
                      </div>
                    {% endfor %}
                  </div>
                </div>
                <div class="d-flex justify-content-center my-4">
                  <input type="submit"
                         class="btn border border-secondary px-4 py-3 rounded-pill text-primary w-100"
                         value="{% trans "Filter" %}">
                </div>
              </div>
            </form>
            <div class="col-lg-9">
              <div class="row g-4 justify-content-center">
                {% for product in products %}
                  {% include "product_card.html" with product=product %}
                {% endfor %}
                <div class="col-12">
                  <div class="pagination d-flex justify-content-center mt-5">
                    {% if page_obj.has_previous %}
                      <a href="?page=1&{{ copied_url.urlencode }}" class="rounded">&laquo; First</a>
                      <a href="?page={{ page_obj.previous_page_number }}&{{ copied_url.urlencode }}"
                         class="rounded">Previous</a>
                    {% endif %}
                    {% for page_num in get_elided_page_range %}
                      {% if page_obj.number == page_num %}
                        <a href="?page={{ page_num }}&{{ copied_url.urlencode }}"
                           class="active rounded">{{ page_num }}</a>
                      {% elif page_num == '...' %}
                        <span class="rounded">...</span>
                      {% else %}
                        <a href="?page={{ page_num }}&{{ copied_url.urlencode }}"
                           class="rounded">{{ page_num }}</a>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}&{{ copied_url.urlencode }}"
                         class="rounded">Next</a>
                      <a href="?page={{ paginator.num_pages }}&{{ copied_url.urlencode }}"
                         class="rounded">Last &raquo;</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Fruits Shop End-->
{% endblock content %}

store/templates/contacts.html
{% extends "base.html" %}
{% block content %}
  <!-- Single Page Header start -->
  <div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">Contact</h1>
    <ol class="breadcrumb justify-content-center mb-0">
      <li class="breadcrumb-item">
        <a href="#">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="#">Pages</a>
      </li>
      <li class="breadcrumb-item active text-white">Contact</li>
    </ol>
  </div>
  <!-- Single Page Header End -->
  <!-- Contact Start -->
  <div class="container-fluid contact py-5">
    <div class="container py-5">
      <div class="p-5 bg-light rounded">
        <div class="row g-4">
          <div class="col-12">
            <div class="text-center mx-auto" style="max-width: 700px;">
              <h1 class="text-primary">Get in touch</h1>
              <p class="mb-4">
                The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a href="https://htmlcodex.com/contact-form">Download Now</a>.
              </p>
            </div>
          </div>
          <div class="col-lg-7">
            {% include "success-message.html" %}
            <form action="{% url "store:contacts" %}" method="POST">
              {% csrf_token %}
              <input type="text"
                     class="w-100 form-control border-0 py-3 mb-4"
                     placeholder="Your Name"
                     id='name'
                     name='name'>
              {% include "partials/error.html" with field_errors=form.name.errors %}
              <input type="text"
                     class="w-100 form-control border-0 py-3 mb-4"
                     placeholder="Enter Your Email"
                     id='email'
                     name='email'>
              {% include "partials/error.html" with field_errors=form.email.errors %}
              <textarea class="w-100 form-control border-0 mb-4"
                        rows="5"
                        cols="10"
                        placeholder="Your Message"
                        id='message'
                        name='message'></textarea>
              {% include "partials/error.html" with field_errors=form.message.errors %}
              <button class="w-100 btn form-control border-secondary py-3 bg-white text-primary "
                      type="submit">Submit</button>
            </form>
          </div>
          <div class="col-lg-5">
            <div class="d-flex p-4 rounded mb-4 bg-white">
              <i class="fas fa-map-marker-alt fa-2x text-primary me-4"></i>
              <div>
                <h4>Address</h4>
                <p class="mb-2">123 Street New York.USA</p>
              </div>
            </div>
            <div class="d-flex p-4 rounded mb-4 bg-white">
              <i class="fas fa-envelope fa-2x text-primary me-4"></i>
              <div>
                <h4>Mail Us</h4>
                <p class="mb-2">info@example.com</p>
              </div>
            </div>
            <div class="d-flex p-4 rounded bg-white">
              <i class="fa fa-phone-alt fa-2x text-primary me-4"></i>
              <div>
                <h4>Telephone</h4>
                <p class="mb-2">(+012) 3456 7890</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Contact End -->
{% endblock content %}

store/templates/product.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
  <!-- Single Page Header start -->
  <div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">{{ product.name }}</h1>
    <ol class="breadcrumb justify-content-center mb-0">
      <li class="breadcrumb-item">
        <a href="#">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="#">Pages</a>
      </li>
      <li class="breadcrumb-item active text-white">Shop Detail</li>
    </ol>
  </div>
  <!-- Single Page Header End -->
  <!-- Single Product Start -->
  <form action="{% url "order:cart_actions" product.id %}"
        method="POST"
        class="container-fluid py-5 mt-5">
    {% csrf_token %}
    <div class="container py-5">
      <div class="row g-4 mb-5">
        <div class="col-lg-8 col-xl-9">
          <div class="row g-4">
            <div class="col-lg-6">
              <div class="border rounded">
                <a href="#">
                  <img src="{{ product.image.url }}"
                       class="img-fluid rounded"
                       alt="{{ product.name }}">
                </a>
              </div>
            </div>
            <div class="col-lg-6">
              <h4 class="fw-bold mb-3">{{ product.name }}</h4>
              <h5 class="fw-bold mb-3">{{ product.price }} $</h5>
              <p class="mb-4">{{ product.description }}</p>
              <button type="submit"
                      class="btn border border-secondary rounded-pill px-4 py-2 mb-4 text-primary">
                <i class="fa fa-shopping-bag me-2 text-primary"></i> {% trans "Add to cart" %}
              </button>
            </div>
            <div class="col-lg-12">
              <nav>
                <div class="nav nav-tabs mb-3">
                  <button class="nav-link active border-white border-bottom-0"
                          type="button"
                          role="tab"
                          id="nav-about-tab"
                          data-bs-toggle="tab"
                          data-bs-target="#nav-about"
                          aria-controls="nav-about"
                          aria-selected="true">{% trans "Description" %}</button>
                </div>
              </nav>
              <div class="tab-content mb-5">
                <div class="tab-pane active"
                     id="nav-about"
                     role="tabpanel"
                     aria-labelledby="nav-about-tab">
                  <p>{{ product.description }}</p>
                  <div class="px-2">
                    <div class="row g-4">
                      <div class="col-6">
                        <div class="row bg-light align-items-center text-center justify-content-center py-2">
                          <div class="col-6">
                            <p class="mb-0">{% trans "Weight" %}</p>
                          </div>
                          <div class="col-6">
                            <p class="mb-0">{{ product.weight }} kg</p>
                          </div>
                        </div>
                        <div class="row text-center align-items-center justify-content-center py-2">
                          <div class="col-6">
                            <p class="mb-0">{% trans "Country of Origin" %}</p>
                          </div>
                          <div class="col-6">
                            <p class="mb-0">{{ product.country_of_origin }}</p>
                          </div>
                        </div>
                        <div class="row bg-light text-center align-items-center justify-content-center py-2">
                          <div class="col-6">
                            <p class="mb-0">{% trans "Quality" %}</p>
                          </div>
                          <div class="col-6">
                            <p class="mb-0">{{ product.quality }}</p>
                          </div>
                        </div>
                        <div class="row text-center align-items-center justify-content-center py-2">
                          <div class="col-6">
                            <p class="mb-0">{% trans "Check" %}</p>
                          </div>
                          <div class="col-6">
                            <p class="mb-0">{{ product.check }}</p>
                          </div>
                        </div>
                        <div class="row bg-light text-center align-items-center justify-content-center py-2">
                          <div class="col-6">
                            <p class="mb-0">{% trans "Min Weight" %}</p>
                          </div>
                          <div class="col-6">
                            <p class="mb-0">{{ product.min_weight }} Kg</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-xl-3">
          <div class="row g-4 fruite">
            <div class="col-lg-12">
              <div class="mb-4">
                <h4>{% trans "Categories" %}</h4>
                <ul class="list-unstyled fruite-categorie">
                  {% for category in category %}
                    <li>
                      <div class="d-flex justify-content-between fruite-name">
                        <a href="{% url "store:products" category.slug %}">{{ category.name }}</a>
                        <span>({{ category.product_count }})</span>
                      </div>
                    </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
  <!-- Single Product End -->
{% endblock content %}